FROM node:20.11.1-slim

WORKDIR /app

COPY . .

RUN npm install -g pnpm@9.9.0
RUN pnpm install --frozen-lockfile --prod --ignore-scripts
RUN pnpm run build

EXPOSE 3000
ENTRYPOINT [ "node" ]
CMD [ "dist/index.js" ]