FROM node:24.14.0-alpine
ENV NODE_ENV=development

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@10.11.0
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000 6379
ENTRYPOINT [ "pnpm", "run" ]
CMD ["start:dev"]