name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Check Build
        run: pnpm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Run tests
        run: pnpm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Run linter
        run: pnpm run lint
